version: '3.8'

services:
  nexus:
    image: docker.io/sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "5000:5000" # docker registry, http
      - "5001:5001" # docker registry, http
      - "5002:5002" # docker registry, https
    volumes:
      - nexus-data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms512m -Xmx2048m -XX:MaxDirectMemorySize=3072m"
    restart: unless-stopped

volumes:
  nexus-data:
